language: node_js

node_js:
  - stable

install:
  - npm install
script:
  - istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && codecov
  - codecov

after_success:
  - bash <(curl -s https://codecov.io/bash)
